version: "3"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db_clj
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  api1:
    build: .
    # image: rinha-clj
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
    ports:
      - "9999:9999"

  # api2:
  #   build: .
  #   depends_on:
  #     - postgres

  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - api1
  #     - api2
  #   ports:
  #     - "9999:9999"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.05'
  #         memory: '128MB'
